spring:
  jpa:
    defer-datasource-initialization: true
  h2:
    console.enabled: true

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
        SQL: DEBUG

server:
  error:
    whitelabel:
      enabled: false